### ISSUE TITLE
Xstreamity crash due to invalid type

### ISSUE THREAD

**Issue by jbx1** [kiddac/XStreamity#15]
Xstreamity crashed with the following log. It seems to be expecting an object that has the method decode, when in fact the object is actually an `int`. 

```
action ->  XStreamityActions cancel
find old format eServiceReference string
find old format eServiceReference string
action ->  XStreamityActions rec
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Plugins/Extensions/XStreamity/live.py", line 1540, in downloadStream
    self.name = NoSave(ConfigText(default=name, fixed_size=False))
  File "/usr/lib/enigma2/python/Components/config.py", line 907, in __init__
    self.value = self.last_value = self.default = default
  File "/usr/lib/enigma2/python/Components/config.py", line 1041, in setValue
    self.text = val.decode("utf-8")
AttributeError: 'int' object has no attribute 'decode'
(PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0x643c0a30>>,('XStreamityActions', 'rec')) failed)
getResolvedKey config.plugins.crashlogautosubmit.sendAnonCrashlog failed !! (Typo??)
resolve: resolve ${sysconfdir}/enigma2/settings
resolve: -> /etc/enigma2/settings
getResolvedKey config.plugins.crashlogautosubmit.addNetwork failed !! (Typo??)
resolve: resolve ${sysconfdir}/enigma2/settings
resolve: -> /etc/enigma2/settings
getResolvedKey config.plugins.crashlogautosubmit.addWlan failed !! (Typo??)
resolve: resolve ${sysconfdir}/enigma2/settings
resolve: -> /etc/enigma2/settings
```

**Comment by kiddac** [comment]
Sorry not logged into github for a while. 
Is this still an issue.  

By the looks of your log this was happeing for you when you were trying to record a live stream.

If its still an issue, let me know what box and image you using. 
Also make sure you have the latest version of xstreamity. I update it all the time.

**Comment by jbx1** [comment]
Sure, let me update it again first. My version is a few months old, so you might have already made quite a few fixes.
